### ISSUE TITLE
How to set up data storage with on-prem s3 and local Metaflow service?

### ISSUE THREAD

**Issue by gaborvecsei** [Netflix/metaflow#1015]
I have "deployed" locally the metaflow service and now I would like to use a on-prem s3 storage for the artifacts.

How should I configure it?

**Comment by valayDave** [comment]
Are you using docker-compose or the `python` command to deploy it ?

**Comment by gaborvecsei** [comment]
I am deploying using the docker images and `docker-compose`

``` shell
# Set up metaflow service
$ git clone https://github.com/Netflix/metaflow-service.git && cd metaflow-service
# Running docker-compose.development.yml (recommended during development):
$ docker-compose -f docker-compose.development.yml up

# Run docker container using custom default API endpoint
$ docker run -p 3000:3000 -e METAFLOW_SERVICE=http://localhost:8083/ metaflow-ui:latest
```

**Comment by rinnadom** [comment]
@gaborvecsei did the suggestion above end up working for you? I'm similarly looking to use local S3 storage with Metaflow.

**Comment by valayDave** [comment]
@gaborvecsei : You need modify the `ui_service`section of the [docker compose file](https://github.com/Netflix/metaflow-service/blob/a9ac9814eaa46882f4d02bb96777608527e66793/docker-compose.development.yml#L18) with the `MF_DATASTORE_ROOT` and  `METAFLOW_DATASTORE_SYSROOT_S3`. you will also have to set `METAFLOW_DEFAULT_DATASTORE=s3` in that file. 

If you have a on-prem s3 that exposes an endpoint URL then you can also set the `METAFLOW_S3_ENDPOINT_URL` to access the S3 bucket via a URL endpoint instead of a s3 like URL.

**Comment by gaborvecsei** [comment]
Thank you very much for the help! It has been successful. <3
