### ISSUE TITLE
Can't use libraries I can't install locally

### ISSUE THREAD

**Issue by ASharmaML** [Netflix/metaflow#1296]
Although on AWS Batch, there should be no problem using libraries which are linux only, metaflow requires me to have a local installation of the library to even attempt to run the flow.

There should be an option to ignore what is installed locally, and only look at what is installed on the specified docker container when deciding whether to run a flow or not. This is quite a typical use-case when someone is developing from MacOS with libraries that don't support MacOS, and I feel it should be supported.

**Comment by romain-intel** [comment]
If I understand your question correctly, the issue you are facing is that you have a flow file that has something like
```
import foobar
from metaflow import FlowSpec
...
```
and you don't have package `foobar` on your Mac.

The issue is that to execute your flow you do something like `myflow.py run` which means that Python reads the entire file, including the import statement to execute it and then barfs on the unknown package.

The solution is to move your import statement inside your step code so something like:
```
@step
def mystep(self):
    import foobar
    # use stuff from foobar
```
which will ensure that the import statement is only executed within the environment for the step (so remotely if you use `--with batch` for example). This also applies if you are using a Conda environment btw.

Does this help or did I misunderstand the question?

**Comment by ianmoss** [comment]
A module cannot be imported at the top of the main script that is not installed locally.

Adding the import within a step partially resolves this however pylint croaks

```
Running pylint...
    my_flow.py:37:8: E0401: Unable to import 'foobar' (import-error)
    Pylint is not happy:
```
    
I have got over this by creating a foobar.py file. This module can then import modules that are not installed locally but that are included in the image for the step.

**Comment by savingoyal** [comment]
@ianmoss you can also run flows with `--no-pylint` to ignore the pylint check (or set `METAFLOW_PYLINT=0` in your environment)
