### ISSUE TITLE
2 minute pause when running a kubernetes step

### ISSUE THREAD

**Issue by ianmoss** [Netflix/metaflow#1318]
When running a step on kubernetes there is a ~2 minute pause during the step execution. It is very apparent in the output on the screen as the log time has a consistent 2 minutes 11 seconds gap during the kubernetes step.

Having investigated the issue its much easier to highlight the line that is causing the pause than describe how to reproduce.

https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/kubernetes/kubernetes_decorator.py#L330

This is waiting for a response from the ec2 instance identity api

https://github.com/Netflix/metaflow/blob/230fc73eb04553cf08d3177cd14ab49b9b4e2859/metaflow/plugins/aws/aws_utils.py#L24

I am using a local kubernetes node so its no real surprise that this api is not responding. I am not totally sure why it retries for 2 minutes but I could likely fix this with some internal network configs - for now I have just commented out getting the ec2 metadata.

The comments say "end-point might be blocked on AWS and not available for non-AWS deployments" so seem to accept that this line maybe run on a non AWS instance.

Either I am missing something fundamental that I have got wrong in the configuration or I need a means to disable off get_ec2_instance_metadata(). Ideally it would be automatic if the node is not on an ec2 instance, or may be it only executes if it is on a AWS instance?

I'll update here if I find an elegant solution, I'd like to hear others thoughts.

**Comment by saikonen** [comment]
Could you check out the quick fix PR I opened regarding this issue. The only change is that it reduces the timeout for the requests significantly, which should get the overhead of running kubernetes steps on non-AWS environments down to 1 sec.

Admittedly this is only half of the solution, as noted in the comments, the instance identity service might be inaccessible even when running on AWS. For the time being we need to try the EC2 metadata request on every kubernetes run as we do not know which cloud provider (if any) is being used.

Going forward we would want to add some way to detect the cloud provider in order to defer from performing unnecessary requests like this, especially since there are plans to fetch instance metadata on GCP and Azure as well.

**Comment by ianmoss** [comment]
I have checked it out, it works a treat when using with local kubernetes I'll certainly vote for it to be merged.

From what I have read, this is the most reliable way of determining if a server is an EC2 instance, remembering to set a timeout.

**Comment by saikonen** [comment]
closing this issue as completed for now, and opening another for future improvements regarding fetching cloud-agnostic instance metadata in a kubernetes native way.
