### ISSUE TITLE
NFS k8s volume mounts 

### ISSUE THREAD

**Issue by DonIvanCorleone** [Netflix/metaflow#1362]
Hello everyone,

its just a short question: I am in needed of mounting a NFS share into my metaflow pods running in kubernetes (on-prem). As I was searching for a solution I stumbled across this referenced line, which basically points to an TODO for @savingoyal 

https://github.com/Netflix/metaflow/blob/e68d63f96181d5916332a1295feb3a57cad7d122/metaflow/plugins/kubernetes/kubernetes_job.py#L185

I guess you are planning to support volume mounts, but are there any chances this might happen anytime soon?

Many thanks for this cool project

Cheers

P.S. and ofcourse this is needed for mountPoints as well ;)

**Comment by DonIvanCorleone** [comment]
As suggested by @saikonen I will try to outline a better understanding of the PR #1364 


**Use-Case**

This PR will enable users to use Network File System (NFS) in their workflows when using Kubernetes. 

NFS are often used in business departments for easy file share, thus can easily evolve into central data storage units holding many GB/TB of data. Using metaflow with local data store and execution would allow for access on NFS but cannot be executed in Kubernetes (with all its benefits). The only known workaround for users would be to re-locate files from their NFS to a S3 storage to have convenient access to their data within their flows.

To prevent re-allocation and transfer of many GB of data from one location to another, using the Kubernetes built-in support for NFS seems to be sensible.

**Comaprison to S3**

As briefly outlined above: S3 is definitely a very good solution in cases where data storage can be "easily" transfered to S3 but in cases NFS are already "heavily" in use S3 cannot be used as "drop-in replacement".   

**Drawbacks & Bottlenecks** 

Nothing to declare :) 

**Expected usage**

`@kubernetes(volumes={"nfs":[{"source":{"path":"/path/on/server", "read_only":True, "server":"SERVER"}, "mount":{"path":"/path/on/container", "read_only":True}}]})`

`volumes` can take a dict of multiple different volume mounts - the above PR only supports NFS! although the tmpfs could be integrated into the above proposed logic which could be discussed ?! 

`volumes={"nfs":[{"source":{"path":"/path/on/server", "read_only":True, "server":"SERVER"}, "mount":{"path":"/path/on/container", "read_only":True}}], "tmpfs":{"mount_path":"/path/to"mount", "size_limit":123}}`
 
`nfs` can take multiple mounts from different locations and map those mounts into the running container
`source` and `mount` specify the mapping from server <-> container.
 
Please note: tmpfs which has been introduced in #1361 remains untouched with respect of how to set parameters etc. It has *not* been integrated into the above `volumes={...}`structure which could be discussed if needed. :)

**Comment by DonIvanCorleone** [comment]
Hi @saikonen 

did you already had some time to check the PR?

All the best
Daniel

**Comment by DonIvanCorleone** [comment]
Hi @saikonen, 

by chance any progress here? 

All the best

**Comment by saikonen** [comment]
Heya, and apologies for taking so long to get back to this. I'm currently contemplating on the proposed usage and how it relates to #1117

Thank you for the insight on the business case for NFS mounts, this completely makes sense. I'm still wondering if there would be other approaches for offering the NFS access for steps that would involve less/no configuration from the flow developer. Have you explored any alternatives for provisioning the volume mount?

If we end up going with the proposal of mounting volumes through the Kubernetes decorator options, some thoughts on that:

- nfs mounts might end up having distinct options compared to other volume types, and your PR also has an explicit method for parsing these. Would it make more sense to have `nfs_volumes=[]` instead of a generic `volumes=` as an option?
- is there a need for separating `read_only` for source/mount sides?
- overall thoughts on reducing nesting in the config? f.ex. `nfs_volumes=[{source_path:"path/on/server", "server": "SERVER_URL", mount_path: "path/to/mount", read_only: True}]`

**Comment by DonIvanCorleone** [comment]
Hi @saikonen,

first of all: Thanks for you feedback, I am happy to share my thoughts on that. 
Let me try to answer each question in order.

> 'm still wondering if there would be other approaches for offering the NFS access for steps that would involve less/no configuration from the flow developer. Have you explored any alternatives for provisioning the volume mount?

Well certainly you can use NFS quite easily on your local machine without involving any of the @kubernetes decorator. But unfortunately this only holds true in local execution cases. The moment your are within the "Kubernetes World" there is no other way around to get access to NFS - at least from my knowledge. This is directly related to how k8s works with volume mounts in general and how these mounts can be provisioned into the running pods/containers.

> nfs mounts might end up having distinct options compared to other volume types, and your PR also has an explicit method for parsing these. Would it make more sense to have nfs_volumes=[] instead of a generic volumes= as an option?

Sure thing, this would be an option. When I started implementing the NFS volume mount option I had in mind, that potentially mixed volume mounts might be of use for others e.g. NFS + azure_disk or any other combination (see list of available volumes with Kubernetes support https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Volume.md). So the main idea was to throw anything related to volumes into that `volmes=` option and within the nested structure to get specific on the details as freely as possible and allow maximum flexibility. 

> is there a need for separating read_only for source/mount sides?

I see your point and I agree it is a bit confusing. I just wanted to follow along the way Kubernetes provides access (please see here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1VolumeMount.md and here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1NFSVolumeSource.md) and indeed it does make sense to have two read_only options - Imagine the NFS volume is mounted into K8s with VolumeMount in a read_only=False (=writeable) mode and two container want to have access to the volume one is allowed to write on the volume the otherone is not. This way you require another `read_only=<bool>` option which is configured on the pod level. Otherwise you would have to mount the volume twice once in read mode and once in write mode which is somewhat inconvenient I guess.  
I know this feels a bit overcomplex, its just what K8s offers :)

> overall thoughts on reducing nesting in the config? f.ex. nfs_volumes=[{source_path:"path/on/server", "server": "SERVER_URL", mount_path: "path/to/mount", read_only: True}]

Yeah I fully agree on your point: The complexity might be really nasty but on the otherhand I wanted to offer as much flexibility to future contributions as possible. The general idea is e.g.:

volumes={nfs_volumes=[], azure_disk=[], aws_elastic_block_store=[]} or any other volume mount or combination of volume mounts can be covered this way.
Each of the volume mounts is a list basically because several different mounts might be needed.
The inlined tuple e.g. nfs_volumes=[{ source=, mount= } basically reflects the k8s need of having such a tuple of V1VolumeMount + V1<XX>VolumeSource.  

Well I hope I could clarify a little bit your questions and I could phrase them at least halfway correct. If somethings still left unclear I am really happy to discuss!! Just let me know

**Comment by DonIvanCorleone** [comment]
One last thing I forgot to mention: 

To reduce the configuration complexity one could require that the volume source is already setup and the @kubernetes decorator only considers configuration of the mount point for the pods being executed (basically the options here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1VolumeMount.md)

**Comment by saikonen** [comment]
Chiming back in after having some discussions yesterday regarding #1117 and how it relates to this use-case. The PVC approach has been suggested as a low-config option for mounting data sources as volumes for steps. In no particular order these are the immediate benefits I can see from using PVC's instead of direct volume mounts
-  greatly simplifies the mount config, keeping resource config out of the flow specs
- keeps infrastructure concerns (connectivity, permissions, throughput) scoped into the Kubernetes resource, which is managed separately from flow specs
- enables the vendor suggested way of accessing managed file services (EFS, Filestore etc.) with a CSI driver+Kubernetes PV&PVC

Would this be a working solution for your use-case with the NFS volumes as well? Roughly the steps required for setting things up with the PR I opened would require:
- Defining the NFS volume as a PersistentVolume in your Kubernetes cluster
- Defining a PersistentVolumeClaim for the volume in your metaflow jobs namespace.

usage in flows would then be as simple as
```
@kubernetes(persistent_volume_claims={"test-pvc-for-nfs": "/mnt/testvol", "pvc-for-different-nfs": "/mnt/data2"})
```

**Comment by DonIvanCorleone** [comment]
To make it short: Yes. This is absolutely fine by me and would be a pretty good trade off.

**Comment by saikonen** [comment]
> To make it short: Yes. This is absolutely fine by me and would be a pretty good trade off.

Excellent. The PVC feature was released yesterday so you can take it for a spin. The PR outlined three different ways of setting the mounts:
```python
# for a specific step with the kubernetes decorator
@kubernetes(persistent_volume_claims={"test-pvc-feature-claim": "/mnt/testvol"})
```
```sh
# globally by passing options to --with kubernetes 
python test.py --with kubernetes:persistent_volume_claims='{"test-pvc-feature-claim": "/mnt/testvol"}' run

# globally by setting an environment variable (stringified json)
METAFLOW_KUBERNETES_PERSISTENT_VOLUME_CLAIMS='{"test-pvc-feature-claim": "/mnt/testvol"}' python test.py run
```

**Comment by saikonen** [comment]
I'll close this issue as resolved for now, but feel free to comment and reopen if it turns out that the PVC mounts are lacking in some way for your use case.
