### ISSUE TITLE
Unit testing steps

### ISSUE THREAD

**Issue by TMiguelT** [Netflix/metaflow#140]
Workflows steps should be able to be unit tested to assure that they're behaving correctly. Currently it doesn't look like there is any mechanism for running tasks in isolation, but this is crucial for allowing unit tests.

It would be ideal if we had a function to let us specify a step, and a set of parameters in the data store to be available, facilitating unit testing. For example:

```python
# Define a workflow we want to test
class Workflow(FlowSpec):
    a = Parameter('a')
    b = Parameter('b')
    @step 
    def start():
        self.c = self.a + self.b
        self.next(self.end)
    @step 
    def end():
        pass

# Run the "start" step in isolation
output_params = run_isolated_step(step=Workflow.start, context={
    'a': 1,
    'b': 1
})
assert output_params['c'] == 2

**Comment by savingoyal** [comment]
@TMiguelT [Gitter thread](https://gitter.im/metaflow_org/community?at=5e5e87fcca2f5a558d62ad96) on this.

- You can separate out business logic from steps in separate Python modules, which you can test with any (unit) testing package for Python.
- You can do integration testing for the whole flow by running the flow (e.g. as a part of a CI/CD pipeline like Jenkins) and then checking that the results are expected by inspecting its artifacts using the Client API (or `dump` in CLI).

**Comment by savingoyal** [comment]
@TMiguelT Please comment and re-open this thread as needed.

**Comment by vfilter** [comment]
Late to the game, but we're currently facing this issue: Most of our workflows have side effects (e.g., database calls, file downloads from S3). 

We would like to do integration testing of the whole workflow. I tried using pytest where I monkeypatch the functions with side effects in my workflows and then run metaflow in a subprocess as described [here](https://outerbounds.com/docs/use-pytest/). Didn't think this through because of course `monkeypatch.setattr` doesn't work in a subprocess, so I'm back to square 1.

@savingoyal do you have any idea on how to approach this? I'd like to avoid having to write some sort of 'if_local' condition into all functions with side effects. It would be much cleaner if I could simply run everything from pytest.

**Comment by Sruthi002** [comment]
How to import the function  'run_isolated_step'?

**Comment by Sruthi002** [comment]
Any leads on how to write unit test cases to test each step using pytest?

**Comment by milesgranger** [comment]
+1 for this, having each step be just a redirection to another part of the code is not great, while there is also the point I want to assert logic of the step as well to verify it initiates another step (or not) based on its logic. I think adding something like click uses in its CLI testing features would be helpful here.
