### ISSUE TITLE
Support resource limits in Kubernetes. 

### ISSUE THREAD

**Issue by roofurmston** [Netflix/metaflow#1544]
Kubernetes provides support for both resource [requests & limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/). At present, Metaflow supports requests only. It would be good if Metaflow could also provide support for limits, as these can be beneficial in certain situations. 

After discussion on Slack, the general idea would be to have a flag (in the Metaflow config) that can be used to switch between the use of either requests or limits. Slack thread can be found [here](https://outerbounds-community.slack.com/archives/C020U025QJK/p1694515923600079).

**Comment by elgehelge** [comment]
While this might solve a few people's problems, I think the suggested solution is still not sufficient.

Requests are “I need at least X”, limits are “I want this pod to use at most Y”. These should not really be exclusive. When using Kubernetes, often you want to specify both of these. So I am a little worried that the suggested solution, will move us to a worse position for making a good solution in the future, because then we end up having this flag which then needs to be deprecated.

**Comment by tfurmston** [comment]
In my experience people tend to use either requests or limits and not both. 

I'm guessing the solution was proposed as adding functionality to specify both requests & limits would have required far more extensive changes to the code base?

**Comment by savingoyal** [comment]
draft PR #2155
