### ISSUE TITLE
Model versioning

### ISSUE THREAD

**Issue by kevhill** [Netflix/metaflow#170]
I'm curious if the following feature is possible in metaflow. I don't think so because of some pretty low-level python limitations, but I figured I would as the community and see if I'm missing something.

A pretty wonderful use case for metaflow would be to standardize the validation of models over time. To do that you would need to load in some saved version of the model, and predict on some new data. 

However, saving and loading data in metaflow relies on pickle, which would evaluate all dependencies at runtime.

So, am I right that this is an unavoidable problem
```
train/1/x - model v 1.0.0
train/2/x - model v 1.0.1

... time passes

validate/1/x - model v 1.0.1, so the flow might fail to load v1.0.0 or load it incorrectly
```

Can metaflow help circumvent this issue in any way?

**Comment by savingoyal** [comment]
@kevhill You can specify and lock down your dependencies using the [`@conda` decorator](https://docs.metaflow.org/metaflow/dependencies#managing-dependencies-with-conda-decorator) for your validation step. That should allow you to reliable execute your validation step.

**Comment by kevhill** [comment]
that would allow me to rerun the step correct? but not say, use a self.model that had been saved to do an additional .predict() on new data

I'm imagining something like this:

```
class TrainFlow(FlowSpec):
...
  @step
  def train(self):
    self.model = SomeModel().fit(some_data)
    self.next(self.end)
...

class ValidateFlow(FlowSpec):
   model_to_validate = Parameter('model_to_validate')
...
  @step
  def validate(self):
    run = Run(model_to_validate)
    run.model.score(some_new_data)
....
```
So while we could give an `@conda` to the `TrainingFlow`, we still would need to have the same model version when loading it in our `ValidationFlow` right?


But I'm guessing you would design this same functionality differently. The goal would be to have a standardized validation flow that could be run on some arbitrary old model that might have different dependencies (but at least as the same interface obviously).

**Comment by savingoyal** [comment]
We are actually working on a feature this quarter (Q2 2020) to essentially enable what you are seeking. `run.model.score` will execute inside its own environment that was defined when the `model` was first generated. @romain-intel can share more details on that front.

**Comment by romain-intel** [comment]
Hi. To provide a bit more detail, as @savingoyal mentioned, we are actually working on a way to access artifacts produced in a conda environment. As you rightly pointed out, an artifact that was saved within a specific environment (model in your TrainFlow) needs to be accessed within that environment again. This is true if you use a Notebook to access it or access it via the client API in another flow (as you do in your ValidateFlow). Currently, for your case, the solution would be to have the validate step run in the same environment as the train step. This is clearly not ideal in large part because we cannot expect the writer of the validate flow to necessarily know what the train flow did.

The solution we are working on would spin up a separate python interpreter in the proper environment (so the conda environment that was used to create the artifact in the first place) and pass all methods on that artifact to that sub-interpreter. There are lots of details and caveats for this but the basic principle has been tested for a different use case within Netflix (it's basically a form of RPC).

We are hoping to develop something in Q2 which would make our Conda solution more complete (right now, artifacts that are pickled in a specific conda environment are hard to access unless you are in that same conda environment).

**Comment by kevhill** [comment]
Great. I haven't looked into how conda handles github installs, but the intended use case for my client is versioning of internal models. Someone needs to overwrite a .fit() to include some hard filters, or have to do something non-standard in another way on top of slowly changing sci-kit learn models. So, hopefully we can point to a github commit for that internal state and don't need to setup our own pypi instance just to get versioning right with conda....

**Comment by romain-intel** [comment]
@kevhill : github installs are also something we are looking at. I'll post a separate issue to track this (it came up internally in a similar form). We do not yet have a great story with conda and github pulls.

**Comment by kevhill** [comment]
Wonderful. fwiw we are still using metaflow for this project with a few minor caveates and work-arounds. The core of it is great and I'm excited to see the development continue. Thanks!

**Comment by baratrion** [comment]
> We are hoping to develop something in Q2 which would make our Conda solution more complete (right now, artifacts that are pickled in a specific conda environment are hard to access unless you are in that same conda environment).

@romain-intel Hi there, is there an update to this? If you use a notebook to access artifacts created within a Conda environment, you need to replicate the same conda environment, right?
