### ISSUE TITLE
metaflow.s3 fails on tljh because of per user /tmp

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#171]
`PermissionError: [Errno 13] Permission denied: '/tmp/metaflow_client/d3/s3objt824hf7n'`

http://tljh.jupyter.org/en/latest/topic/security.html#per-user-tmp

More context - 
https://gitter.im/metaflow_org/community?at=5e85b07454f5db5550290ffe and https://gitter.im/metaflow_org/community?at=5e8715fd4e14eb618b9a87d9

**Comment by shouryaps** [comment]
@savingoyal This issue is because of a multi-user scenario. The first user who creates a folder inside`/tmp` (`metaflow_client` folder in this case) has both read/write access, while other users will have just read access, but will get a permission error when creating files inside metaflow_client folder. 

To resolve this, there can be two solutions:
1) Change cache directory to `/tmp/$USER/metaflow_client` instead of `/tmp/metaflow_client`
This way each user's metaflow client will have its different cache directory and such permission issues will not come.
($USER environment variable is available in both macOS and Linux)
2) Another solution would be to change the permission of the complete folder `/tmp/metaflow_client` to `0777` using python's `os.chmod` function, by the user who creates it first.

A similar issue happened with [tensorboard](https://github.com/tensorflow/tensorboard) [(see issue here)](https://github.com/tensorflow/tensorboard/issues/2010), and they resolved it with the second solution stated above [(see PR here)](https://github.com/tensorflow/tensorboard/pull/2131).

**Comment by savingoyal** [comment]
@shouryaps Yes, I would advocate for the second solution as well. Also you can work around the issue currently by setting the env variable `METAFLOW_CLIENT_CACHE_PATH ` to `/tmp/$USER/metaflow_client`. Let us know if that works for you, otherwise, we will prioritize this fix.

**Comment by shouryaps** [comment]
Yes, setting the METAFLOW_CLIENT_CACHE_PATH to `/tmp/<USERNAME>/metaflow_client` for every user in metaflow config file solved the problem for us for now.

**Comment by jagrit-varshney** [comment]
In addition to what @shouryaps mentioned, we'll also test and monitor everything using this solution for a couple of days and will see if there are some edge cases for this solution.

**Comment by savingoyal** [comment]
@jagrit-varshney Any updates? Please re-open this issue if ran into any issues.
