### ISSUE TITLE
[Question] Specify where to save/load the flow runs results

### ISSUE THREAD

**Issue by alvations** [Netflix/metaflow#219]
From the playlist tutorial:

```
$ metaflow tutorials pull
$ cd metaflow-tutorials
$ python 01-playlist/playlist.py run
```

After running the flow several times, when inspecting the results from the jupyter notebook.

```
$ jupyter-notebook 01-playlist/playlist.ipynb
```

Somehow the 

```python
>>> from metaflow import Flow, get_metadata
>>> print("Current metadata provider: %s" % get_metadata())
Current metadata provider: local@/Users/username/git-stuff/metaflow-tutorials

>>> list(Flow('PlayListFlow').runs())

Out[9]:
[Run('PlayListFlow/1592447243350734'),
 Run('PlayListFlow/1592447235444329'),
 Run('PlayListFlow/1592447213340108')]
```

After some inspection, it seems like Metaflow are saving the run results in:

```
$ ls .metaflow/PlayListFlow/
1592447213340108/  1592447243350734/  data/              
1592447235444329/  _meta/             latest_run 
```

**Comment by seeravikiran** [comment]
We do allow you to control the root directory for the local datastore via `METAFLOW_DATASTORE_SYSROOT_LOCAL`.
This is probably not exposed by `metaflow configure` so you could pre-pend your command executions by setting the value you like.

IIUC - you will still see a `.metaflow` under that root; instead of the cwd (current working directory); if you follow this suggestion.
See this (related) method:
https://github.com/Netflix/metaflow/blob/c2f70c73782549fdce6c418410ecd9b305199b28/metaflow/datastore/local.py#L35

Does this answer your question?
cc @savingoyal

**Comment by alvations** [comment]
Thanks @seeravikiran for the pointer to the `METAFLOW_DATASTORE_SYSROOT_LOCAL` environmental variable! Yes I think I got where the datastore are accessed now.

Oh cool! I can try duck-typing the `LocalDataStore` too https://github.com/Netflix/metaflow/blob/master/metaflow/datastore/local.py  and I guess this is where the datastore is accessed https://github.com/Netflix/metaflow/blob/master/metaflow/main_cli.py#L108 

Thanks @seeravikiran @savingoyal !!
