### ISSUE TITLE
Is there any way to use private image from Dockerhub?

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#319]
When I want to use my own private docker image from Dockerhub I get the error that I need to login. I don't know any other way to login but to enter a password via interactive command-line tool.

Is there any way to do that?

**Comment by savingoyal** [comment]
A couple of different approaches - 
- You can create your own unmanaged AWS Batch compute environment and embed your [docker credentials in the underlying ECS task](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth-container-instances.html) so that AWS Batch can easily pull your private image
- A hacky but simpler approach would be to [copy over your images from Dockerhub into ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html).

**Comment by smolendawid** [comment]
I understand, thank you
