### ISSUE TITLE
"Task is starting (status RUNNABLE)..." for a long time

### ISSUE THREAD

**Issue by smolendawid** [Netflix/metaflow#347]
I have a message 

> Task is starting (status RUNNABLE)...

repeating for a long time, without any follow up, when I want to run a program on AWS batch. Sometimes, however, it seems to work. 

I have no idea how to debug it.  Any ideas?

**Comment by savingoyal** [comment]
@smolendawid This can happen due to a bunch of different reasons. Unfortunately, AWS Batch does not make it super easy to diagnose this currently. Have you checked whether the resources you are asking for the task are available in your compute environment? Also, this article might be helpful - https://aws.amazon.com/premiumsupport/knowledge-center/batch-job-stuck-runnable-status/

**Comment by smolendawid** [comment]
I will try to play with the resources but I can't see any problems yet.

**Comment by smolendawid** [comment]
I think my problem was that I didn't pass the environmental variable `AWS_DEFAULT_REGION`
