### ISSUE TITLE
Terraform support for infra configuration

### ISSUE THREAD

**Issue by sandman21dan** [Netflix/metaflow#38]
Currently the only automated way to spin up AWS infra is via https://github.com/Netflix/metaflow-tools/blob/master/aws/cloudformation/metaflow-cfn-template.yml

A lot of companies have adopted Terraform instead of CloudFormation and would be nice to get easier buy-in from other departments

**Comment by savingoyal** [comment]
@zcking is working on a terraform template - https://gitter.im/metaflow_org/community?at=5dee749f8e906a1c8d9afc49

**Comment by zcking** [comment]
@sandman21dan it's still a work in progress (finding time after work), but I pushed the repo yesterday: https://github.com/zcking/metaflow-terraform

I'm having a 403 Unauthorized permission when trying to run the #05 tutorial right now. Made some tweaks to it last night that I haven't tried yet, but will pick it back up this evening.

**Comment by notadamking** [comment]
@zcking any progress on this?

**Comment by dr3s** [comment]
I modified it for my own purpose.  Thanks for the good work @zcking .  I primarily wanted to separate networking, since ours is already created.  

The final piece that seems to be missing is the load balancer or cname.

**Comment by wtanner** [comment]
I have been evaluating Metaflow for several use cases, and I recently wrote about my [personal setup](https://wtanner.github.io/metaflow/terraform/2020/08/02/personal-metaflow.html), which includes a [Terraform module](https://github.com/wtanner/personal-metaflow) that meets my requirements for my personal projects. In this setup, I opted to not run a Metadata service, since I don't yet have a use for it. It also is opinionated about networking, since I run this in a separate VPC and decided to bundle it all together. There are several other features that are likewise opinionated and not generalized.

I am beginning the process of evaluating Metaflow for professional infrastructure, the outcome of which I expect to be a more general Terraform module. This would include the Metadata service, and probably an optional network setup, since I suspect many users have existing AWS infrastructure.

**Comment by mtx2d** [comment]
> I have been evaluating Metaflow for several use cases, and I recently wrote about my [personal setup](https://wtanner.github.io/metaflow/terraform/2020/08/02/personal-metaflow.html), which includes a [Terraform module](https://github.com/wtanner/personal-metaflow) that meets my requirements for my personal projects. In this setup, I opted to not run a Metadata service, since I don't yet have a use for it. It also is opinionated about networking, since I run this in a separate VPC and decided to bundle it all together. There are several other features that are likewise opinionated and not generalized.
> 
> I am beginning the process of evaluating Metaflow for professional infrastructure, the outcome of which I expect to be a more general Terraform module. This would include the Metadata service, and probably an optional network setup, since I suspect many users have existing AWS infrastructure.

Thanks for writing this up and share your valuable experience! 
I am evaluating Metaflow for my team but am not very familiar with Terraform, do you know how much work it make take to create the "professional".tf?

**Comment by savingoyal** [comment]
@mtx2d If you are okay with cloudformation, we have [an official template](https://github.com/Netflix/metaflow-tools/tree/master/aws/cloudformation) for that.

**Comment by mtx2d** [comment]
> @mtx2d If you are okay with cloudformation, we have [an official template](https://github.com/Netflix/metaflow-tools/tree/master/aws/cloudformation) for that.

@savingoyal, thanks for the reference to cloudformation template. 
Unfortunately, the company I work for has invested in terraform heavily, so continue to use terraform is the only way forward for my current situation.

**Comment by mtx2d** [comment]
I also found a tf PR for this but in a different repo: https://github.com/Netflix/metaflow-tools/pull/14/

**Comment by savingoyal** [comment]
Thanks to the excellent work by @kldavis4, @greghilstonhop and @queueburt, you can now deploy all the cloud resources for Metaflow through a [Terraform template](https://admin-docs.metaflow.org/metaflow-on-aws/deployment-guide#the-simple-approach-deploy-with-aws-cloudformation-or-terraform) 🎉
