### ISSUE TITLE
Can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by Viveckh** [Netflix/metaflow#391]
Been seeing the following error on my flow.

## Context
Essentially I had stored dataframes to `self.x, self.y` variables within a parallelized function triggered through foreach, hoping each parallel call will maintain its own copy that I can access later. These variables are not initialized/referenced/used anywhere outside that step.

## Hypothesis
I do store a bunch of large dataframes, not sure if that is the reason for causing it.

![image](https://user-images.githubusercontent.com/9113166/100771501-7b4e3500-33cc-11eb-81aa-0fd6d778df48.png)

**Comment by tuulos** [comment]
Hi @Viveckh ! This happens when you assign a complex object (maybe your dataframe) to `self.` that doesn't support pickling. A workaround is to use the object's native serialization function to convert the object to a `bytes` object and store the `bytes` in `self.` instead. On the reading side, you'll need to deserialize the `bytes`.

You can have a set of helper functions like `self.df = save_dataframe(my_dataframe_object)` and `df = load_dataframe(self.df)` to make this easier.

We have plans to handle serialization of large dataframes better automatically but this approach will work for any complex objects (e.g. Keras models, which have hit a similar issue).

**Comment by Viveckh** [comment]
Thank you @tuulos for the prompt and thorough response, that was very helpful.

An unrelated question - Is it possible to override `namespace` while kicking off a flow. Or a way to access the `tag` of current flow from within while it is running?

**Comment by Viveckh** [comment]
For anyone who encounters this, in my case, it was not the pandas dataframes but instead instances of my custom python classes that I was assigning to `self.` variables. And I guess they couldn't be serialized cause those class instances were storing db connections and such.

**Comment by ksachdeva11** [comment]
I am facing this similar issue while using Lime with Metaflow.

`self.explainer = lime.lime_tabular.LimeTabularExplainer(X.values, feature_names=X.columns.tolist())`

Wondering how could this be resolved. Any help would be appreciated.
Thanks
