### ISSUE TITLE
Support for LocalDataStore clean-up

### ISSUE THREAD

**Issue by tduffy000** [Netflix/metaflow#41]
It doesn't appear that there is support within the Metaflow framework to clean out/purge the `.metaflow` directory created when running through `FlowSpec`s locally. I imagine such a command might be a useful extension of the CLI given that data scientists using Metaflow might not always audit their hidden local directories.

**Comment by savingoyal** [comment]
@romain-intel can you take this up?

**Comment by tduffy000** [comment]
@savingoyal @romain-intel happy to help out if there's a need.

**Comment by romain-intel** [comment]
Hello @tduffy000 , when you say "clean-up" do you simply mean "rm -rf .metaflow" (or something like that)? So in effect, add a command to the metaflow cli to say metaflow metadata clean (which would restore you to a pristine state -- removing all knowledge of runs and all artifacts)?

**Comment by tduffy000** [comment]
I think that would be a pretty straightforward way to do it (though that sounds more like a `purge` to me than `clean`). 

That said, I imagine it would be nice for people to run the `rm -rf` equivalent on just a particular step (and, thus, any steps dependent on that one). Metaflow nicely prints out all the step names so I don't think it would be too difficult to implement such a logic (I can read into this more) and make intuitive sense to a user. For example, we might want to keep the checkpoint after some feature engineering step but throw out a model step we tried, but ultimately don't need/want.

For example, (just using the FlowSpec in the tutorial,
I.e. `metaflow metadata clean PlayListFlow --step end`
If I want to change the logic of how the recommendations get generated (I realize this isn't really a great example). 

Not to say a global `clean`/`purge` wouldn't also be a nice addition. Curious as to your thoughts @romain-intel .

**Comment by romain-intel** [comment]
The issue of "cleaning out" artifacts was also raised in #35 and @savingoyal gave a few suggestions there. I think it is best to not clear out artifacts selectively (that could lead to weird breakages down the line because of the expectation that artifacts are there (not to mention propagating things down would also be difficult if ou cleaned an intermediate step). I think your PR (#51 ) is a perfectly good approach for a full clean though.

**Comment by sxooler** [comment]
Hello guys, I would prefer to have this support as well, I was thinking about three examples (partially covered by your discussion):

1. Full clean-up
2. Selective clean-up (e.g. I have a successful run and I only need the last results from the end step and all previous might be deleted)
3. Run pruning (remove particular run for the given flow I'm not interested in anymore)

I agree the PR #51 is a good approach for the first point, thanks! Not sure about a point (2) it would need probably major change in how metaflow works at the moment as you have written. What about the last one? I think it could be implemented without big overhead. I sometimes have plenty of 'test runs' and it would be helpful to save my local space just by removing those runs (e.g. by id or by a tag).

**Comment by savingoyal** [comment]
@sxooler and others, the value prop of metaflow is in storing all artifacts so that they can be referenced anytime later. All the data artifacts for a flow are content-addressed so there is no duplication. Full clean-up (1.) can be handled by the user as a special case by issuing an `rm -rf`. Selective clean-up (2. and 3.) is a slippery slope because you end up losing lineage of your executions. We recommend using `s3` as the backing datastore and if data storage costs are still a concern, you can always put an appropriate TTL on the object.

**Comment by tduffy000** [comment]
@savingoyal Feel free to close the issue then. My only concern was the lack of visibility of a hidden directory (here `.metaflow`) and essentially providing some easy way within the framework to remove it given that plenty of end-users might not be familiar enough to check for it and then run an `rm -rf`.
