### ISSUE TITLE
minutes_between_retries not respected with Step Functions

### ISSUE THREAD

**Issue by lsimoneau** [Netflix/metaflow#678]
It seems that when deploying to Step Functions, the `@retry` decorator `minutes_between_retries` option is not used, so retries happen immediately regardless of the setting.

**Comment by lsimoneau** [comment]
I don't fully understand the code, but it looks like there should be a `retry` field in [this object](https://github.com/Netflix/metaflow/blob/master/metaflow/plugins/aws/step_functions/step_functions.py#L769) corresponding to [these options](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html#error-handling-retrying-after-an-error), instead of relying on the Batch `RetryStrategy` which doesn't have any concept of a retry interval?

**Comment by savingoyal** [comment]
@lsimoneau That's a valid observation. We rely on AWS Batch's retry mechanisms rather than AWS Step Functions' retry mechanisms. 

A major reason for that is that we need a consistent Metaflow Task ID for retried tasks - currently, for the AWS Step Functions integration - the AWS Batch job id is used as that consistent Task ID and the attempts within that job is used as the attempt id. If we relied on AWS Step Functions to handle the retries, we would have to find a different identifier to use as the Task ID (one which stays consistent across retries). 

Another reason is that we use sub-workflows within Step Functions (to support branches & for-eaches) and the retry mechanisms of Step Functions will force a retry of the entire sub-workflow in a few scenarios. There doesn't seem to be an easy way to avoid that. 

Given these constraints, we decided that trading away `minutes_between_retries` was worth the effort of keeping the implementation as clean as possible (although I will admit the current implementation is quite hairy)

**Comment by lsimoneau** [comment]
@savingoyal thanks for the detail. The issue we're having is that the transient failures are due to rate limits (in our case Athena concurrent query limits, but this could be any API limit), so the inability to set a retry interval leads to the retries failing. Understand this is a big undertaking if it breaks the reliance on Task IDs. In the interim it probably makes sense to at least update documentation to make this clear, currently [this](https://docs.metaflow.org/metaflow/failures#maximizing-safety) says:

>By default, retry will retry the step for three times before giving up. It waits for 2 minutes between retries on the cloud. This means that if your code fails fast, any transient platform issues need to get resolved in less than 10 minutes or the whole run will fail. Typically 10 minutes is more than enough but sometimes you want both a belt and suspenders.

**Comment by savingoyal** [comment]
That's a good catch. I will push an update to the docs. Usually, there is a latency of few seconds (or more, depending on the compute environment) in between user code retries (AWS Batch scheduling delay + Metaflow setting up the necessary environment). One option for your use case could be to wrap your Athena calls within a process local retry.
