### ISSUE TITLE
Add filename in IncludeFile

### ISSUE THREAD

**Issue by emilyinamillion** [Netflix/metaflow#786]
Hello, I am attempting to use IncludeFile to load a json config. The path name and directory structure is important in my config files. From looking at the source code it appears that the path is never made an attribute of IncludeFile? I attempted then to use sys.argv to collect my pathname but noticed this behavior stops that from behaving as expected. Please let me know if it's just an attribute I'm missing that can be easily used. 

Also, printing out `print(self.myfile.title().lower())` (which produces the parameter name in Parameter()) produces an empty b'' in IncludeFile(). 

**My test flow**
<img width="488" alt="Screen Shot 2021-10-26 at 11 51 58 AM" src="https://user-images.githubusercontent.com/4432805/138942655-059a0a89-f3f6-468e-8477-8eae846c903c.png">

**My cl output**
<img width="1385" alt="Screen Shot 2021-10-26 at 11 48 33 AM" src="https://user-images.githubusercontent.com/4432805/138943260-7c39ec67-2671-4a64-8155-5132d5b7fb77.png">

**Comment by romain-intel** [comment]
Hello @emilyinamillion, apologies for the delay in responding. You are correct that, as of now, the name of the file being included is *not* stored anywhere and using sys.argv will not work as you noted since Metaflow will actually launch a sub-process everytime a task is executed. If you absolutely must get the name of the file currently, the best way would be to pass it as another parameter (not an include file here). Or, if this is a JSON file, you could have it refer to itself (add a field called "filename" or something and store it there).

We have, however, been discussing whether or not to store the name of the file to allow the user to know what the file is about so we may add that. I will keep this issue open as a "add filename as an attribute of IncludeFile"

**Comment by tuulos** [comment]
[The new `Config` feature](https://docs.metaflow.org/metaflow/configuring-flows/introduction) provides a much more robust and versatile way to include configs. You could write [a custom parser](https://docs.metaflow.org/metaflow/configuring-flows/parsing-configs) that includes the config filename in an artifact, together with the config itself
