### ISSUE TITLE
Add GH tests for all supported versions of Python and R

### ISSUE THREAD

**Issue by savingoyal** [Netflix/metaflow#923]
Metaflow currently supports Py>=3.4 (with limited support for Py2.7) and R>=3.8. The GH tests only test for Py3.7 and R4.1. We should ensure we test on the whole set of permutations.

**Comment by hamelsmu** [comment]
Trying this [here](https://github.com/hamelsmu/metaflow/runs/5017277283?check_suite_focus=true)

**Comment by hamelsmu** [comment]
@savingoyal do we want all tests to pass before opening a PR?  Some PRs are breaking for example because of the [presence of `f-strings`](https://github.com/hamelsmu/metaflow/runs/5017349844?check_suite_focus=true#step:6:60)

![image](https://user-images.githubusercontent.com/1483922/151930320-5d458037-ccb1-49de-b16d-4f497ac1358f.png)


![image](https://user-images.githubusercontent.com/1483922/151930215-90ac3aa0-a0de-4b15-97f5-25b5786b5d88.png)

**Comment by tfurmston** [comment]
Looks like this one can be closed by [https://github.com/Netflix/metaflow/pull/946](https://github.com/Netflix/metaflow/pull/946)?
