### ISSUE TITLE
multiple files load in IncludeFile

### ISSUE THREAD

**Issue by herruli** [Netflix/metaflow#96]
I would like to know is there a way to include multi-files in same directory? As currently it only supports single file. Thanks

**Comment by savingoyal** [comment]
Currently, it only supports a single file. You can always include files in the same directory as the flow by using `[--package-suffixes](https://github.com/Netflix/metaflow/blob/c2f70c73782549fdce6c418410ecd9b305199b28/metaflow/cli.py#L678)`

**Comment by romain-intel** [comment]
What is your specific use case?
You can of course use IncludeFile multiple times to include multiple files but I suspect you are looking for something different? What would your desired semantic be (should all the files be appended to one another, etc)?

As a side note, please note the difference between ```--package-suffixes``` and IncludeFile: IncludeFile will create an artifact and load the file into that artifact whereas ```--package-suffixes``` will include the file in the code package created when running on batch.

**Comment by herruli** [comment]
Well, in some cases, I would like to parse a list of documents to perform a series of NLP analysis (eg. sentence separation, classification etc). In this case, includeFile might not be sufficient enough to support it.

**Comment by romain-intel** [comment]
To make sure I understand your use case, you would ideally like to specify something like 'my_input_files_*.txt' as the files to include (which would match, files my_input_files_1.txt, my_input_files_2.txt... for example) and have those be read and imported into multiple artifacts (one for each of the file you read).

**Comment by herruli** [comment]
correct

**Comment by romain-intel** [comment]
Got it. Let me see what I can do. Let me think if it should produce one artifact (a dictionary for example mapping the file name to the loaded file) or multiple single artifacts. The advantage of the first approach is that it is a bit more flexible (you don't need to know the names of all the artifacts initially). The second approach is a bit cheaper because the lazy loading of artifacts will make sure that you only load the file you need (as opposed to all the files). Maybe the ideal approach would be a cross between the two and have something like IncludeMultipleFile which would produce multiple artifacts of which a set of names loaded (or something akin to that) and then all the other file artifacts so it would be something like this: 
`loaded_files = IncludeMultipleFile(
        'loaded_files',
        is_text=True,
        help='My input files',
        default='/Users/bob/my_input_files_*.txt')

@step
def some_step(self):
    for artifact_name, source_file in self.loaded_files:
        print("File %s was loaded in artifact %s" % (source_file, artifact_name))
        print('Hash of file is %s' % str(hashlib.sha1(getattr(self, artifact_name).hexdigest()))
`

This should make it somewhat easy to, for example, do a foreach on all the loaded files and only loading the file you need in the foreach step.

Would something like this meet your need?

**Comment by herruli** [comment]
yes! Thanks

**Comment by romain-intel** [comment]
The `IncludeFile` has undergone a lot of rewrites over time and always with a bit of trepidation. Given the age of this issue and the possible workarounds, I'll close for now but please re-open if you still have a strong use case.
